import React from 'react';
import {AbsoluteFill, Audio, interpolate, Sequence, staticFile, useCurrentFrame} from 'remotion';
import {ColdOpen} from './scenes/ColdOpen';
import {Ride} from './scenes/Ride';
import {Portrait} from './scenes/Portrait';
import {Charge} from './scenes/Charge';
import {TitleCard} from './scenes/TitleCard';
import {Grain, Letterbox} from './components/Effects';

/**
 * 15 seconds at 30fps. Scenes overlap by a few frames so each cut lands on a
 * cross-dissolve rather than a hard seam.
 */
export const SCENES = [
  {Component: ColdOpen, from: 0, duration: 96},
  {Component: Ride, from: 92, duration: 126},
  {Component: Portrait, from: 214, duration: 90},
  {Component: Charge, from: 300, duration: 74},
  {Component: TitleCard, from: 370, duration: 80},
] as const;

/** Short dissolve on the way in so cuts breathe instead of snapping. */
const Dissolve: React.FC<{frames: number; children: React.ReactNode}> = ({frames, children}) => {
  const frame = useCurrentFrame();
  const opacity = interpolate(frame, [0, frames], [0, 1], {
    extrapolateLeft: 'clamp',
    extrapolateRight: 'clamp',
  });
  return <AbsoluteFill style={{opacity}}>{children}</AbsoluteFill>;
};

export const Teaser: React.FC = () => (
  <AbsoluteFill style={{background: '#000'}}>
    {/* Score is generated by scripts/make-audio.mjs and locked to these cuts. */}
    <Audio src={staticFile('score.mp3')} />
    {SCENES.map(({Component, from, duration}, i) => (
      <Sequence key={i} from={from} durationInFrames={duration}>
        <Dissolve frames={i === 0 ? 1 : 8}>
          <Component duration={duration} />
        </Dissolve>
      </Sequence>
    ))}
    <Grain opacity={0.1} />
    <Letterbox height={86} />
  </AbsoluteFill>
);
